# Generated by Django 5.2.14 on 2026-05-24 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_mode', models.CharField(choices=[('rsvp', 'RSVP'), ('bionic', 'Bionic')], default='rsvp', max_length=10)),
                ('default_wpm', models.PositiveIntegerField(default=300)),
                ('default_font', models.CharField(choices=[('inter', 'Inter'), ('opendyslexic', 'OpenDyslexic'), ('system', 'System')], default='inter', max_length=20)),
                ('default_bold_intensity', models.FloatField(default=0.5)),
                ('default_chunk_size', models.PositiveIntegerField(default=1)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('sepia', 'Sepia')], default='dark', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('rsvp', 'RSVP'), ('bionic', 'Bionic')], default='rsvp', max_length=10)),
                ('wpm', models.PositiveIntegerField(default=300)),
                ('bold_intensity', models.FloatField(default=0.5)),
                ('font', models.CharField(default='inter', max_length=20)),
                ('chunk_size', models.PositiveIntegerField(default=1)),
                ('last_position', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='documents.document')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
