# Generated by Django 5.2.14 on 2026-05-24 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='readingsession',
            index=models.Index(fields=['user', 'document'], name='reader_read_user_id_537286_idx'),
        ),
        migrations.AddIndex(
            model_name='readingsession',
            index=models.Index(fields=['user', 'started_at'], name='reader_read_user_id_cdd61b_idx'),
        ),
    ]
