# Generated by Django 5.2.14 on 2026-06-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='default_font',
            field=models.CharField(choices=[], default='inter', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('sepia', 'Sepia'), ('high-contrast', 'High Contrast'), ('dyslexia', 'Dyslexia-Friendly'), ('low-stim', 'Low Stimulation'), ('warm-night', 'Warm Night'), ('cool-focus', 'Cool Focus'), ('solarized-dark', 'Solarized Dark'), ('solarized-light', 'Solarized Light'), ('catppuccin-mocha', 'Catppuccin Mocha'), ('catppuccin-latte', 'Catppuccin Latte'), ('gruvbox-dark', 'Gruvbox Dark'), ('gruvbox-light', 'Gruvbox Light'), ('nord', 'Nord'), ('dracula', 'Dracula'), ('everforest', 'Everforest'), ('tokyo-night', 'Tokyo Night')], default='dark', max_length=30),
        ),
    ]
