# Generated by Django 5.2.14 on 2026-06-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_expand_fonts_and_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('noise', 'Color Noise'), ('ambient', 'Ambient Soundscape')], default='noise', max_length=10)),
                ('noise_type', models.CharField(blank=True, choices=[('white', 'White Noise'), ('pink', 'Pink Noise'), ('brown', 'Brown Noise')], max_length=10, null=True)),
                ('audio_url', models.URLField(blank=True, help_text='CDN URL for ambient tracks. Null for generated noise.', max_length=500, null=True)),
                ('icon', models.CharField(default='🔊', help_text='Emoji icon for the UI', max_length=10)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('volume_default', models.FloatField(default=0.5, help_text='Default volume 0.0-1.0')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated: adhd-i,adhd-c,focus,calm', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='reader_audi_categor_b41cdd_idx')],
            },
        ),
    ]
