# Generated by Django 5.2.14 on 2026-06-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_add_audio_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='default_noise_slug',
            field=models.CharField(blank=True, default='pink-noise', help_text='Default noise track slug', max_length=100),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='noise_enabled',
            field=models.BooleanField(default=True, help_text='Auto-play background noise when reading'),
        ),
    ]
