# Generated by Django 5.2.14 on 2026-06-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_add_noise_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='adhd_subtype',
            field=models.CharField(choices=[('none', 'No ADHD / Prefer not to say'), ('inattentive', 'ADHD — Inattentive (easily distracted, lose focus)'), ('hyperactive', 'ADHD — Hyperactive (restless, fidgety)'), ('combined', 'ADHD — Combined (both)')], default='none', help_text='Used for per-type noise and focus adaptation', max_length=12),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='sensory_sensitivity',
            field=models.CharField(choices=[('low', 'Low — loud/bright is fine'), ('medium', 'Medium — average sensitivity'), ('high', 'High — easily overstimulated')], default='medium', help_text='Affects noise volume, nudge intensity, and theme defaults', max_length=6),
        ),
    ]
