# Generated by Django 5.2.14 on 2026-06-09 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_add_kanban_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('color', models.CharField(choices=[('default', 'Default'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('purple', 'Purple')], default='default', max_length=10)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_archived'], name='reader_note_user_id_a61554_idx'), models.Index(fields=['user', '-updated_at'], name='reader_note_user_id_11888d_idx')],
            },
        ),
    ]
