# Generated by Django 5.2.14 on 2026-06-09 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_add_cowork_rooms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('xp_to_next_level', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User XP',
                'verbose_name_plural': 'User XP',
            },
        ),
        migrations.CreateModel(
            name='DailyReadingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('words_read', models.PositiveIntegerField(default=0)),
                ('minutes_read', models.PositiveIntegerField(default=0, help_text='Estimated reading minutes')),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('sessions_count', models.PositiveIntegerField(default=1, help_text='Number of reading sessions that day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='reader_dail_user_id_f62791_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('words_read', 'Words Read'), ('sprint_complete', 'Sprint Complete'), ('streak_bonus', 'Streak Bonus'), ('daily_goal', 'Daily Goal')], max_length=20)),
                ('xp_amount', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="e.g., {'words': 250, 'document_id': 5}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='reader_xpev_user_id_5f75d0_idx'), models.Index(fields=['user', 'event_type'], name='reader_xpev_user_id_215fd0_idx')],
            },
        ),
    ]
