# Generated by Django 5.2.14 on 2026-06-09 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_add_folder_and_tags'),
        ('reader', '0010_add_xp_and_streak'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(help_text='Question, prompt, or highlighted text')),
                ('back', models.TextField(blank=True, default='', help_text='Answer, definition, or notes')),
                ('source_text', models.TextField(blank=True, default='', help_text='Original highlighted passage')),
                ('source_index', models.PositiveIntegerField(default=0, help_text='Word index in source document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(blank=True, help_text='Next scheduled review (spaced repetition)', null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5, help_text='Spaced repetition ease factor (2.5 = default)')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='reader.flashcarddeck')),
            ],
            options={
                'ordering': ['next_review', '-created_at'],
            },
        ),
    ]
