# Generated by Django 5.2.14 on 2026-06-09 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_add_folder_and_tags'),
        ('reader', '0011_add_flashcards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start_index', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#fbbf24', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document', 'start_index'],
                'indexes': [models.Index(fields=['user', 'document'], name='reader_high_user_id_ced45c_idx'), models.Index(fields=['user', '-created_at'], name='reader_high_user_id_9d4d67_idx')],
            },
        ),
    ]
