# Generated by Django 5.2.14 on 2026-06-09 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(max_length=500, upload_to='figures/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, max_length=500, upload_to='figures/thumbnails/%Y/%m/')),
                ('caption', models.TextField(blank=True, default='', help_text='Detected caption text near the figure')),
                ('figure_number', models.CharField(blank=True, default='', help_text="e.g., '1', '2.3', 'A'", max_length=20)),
                ('reference_text', models.CharField(blank=True, default='', help_text="How it's referenced in text: 'Figure 1', 'Fig. 1'", max_length=100)),
                ('bounding_box', models.JSONField(blank=True, help_text='{x0, y0, x1, y1} on page', null=True)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='documents.document')),
            ],
            options={
                'ordering': ['sort_order', 'page_number'],
                'indexes': [models.Index(fields=['document', 'page_number'], name='documents_f_documen_b518af_idx')],
            },
        ),
    ]
