# Generated by Django 5.2.14 on 2026-06-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_add_folder_and_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB')], default='pdf', max_length=10),
        ),
    ]
